
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"salman@gmail.com",
    "password":"password"  
}

### login user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"salman@gmail.com",
    "password":"password"  
}

### get current user data
GET http://localhost:3000/auth/whoami

### signout current user
get http://localhost:3000/auth/signout


### find all user
GET http://localhost:3000/auth/all


### find user
GET http://localhost:3000/auth/3


### find all user with a given email
GET http://localhost:3000/auth?email=asd@asc.com


### remove the user
delete http://localhost:3000/auth/2


### update the user
patch http://localhost:3000/auth/3
Content-Type: application/json

{
    "password":"salman123"   
}


# ### set color
# GET http://localhost:3000/auth/colors/red


# ### get color
# GET http://localhost:3000/auth/colors
